project:
  type: website
  output-dir: site

website:
  title: "Proteomics blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/LKittinun/LKittinun.github.io
format:
  html:
    theme: flatly
    css: styles.css
open-graph:
    title: "Proteomics blog"
    description: "A blog for sharing ideas, experiences, and knowledge in proteomics—whatever I’m exploring, working on, or feel like writing about."
    image: "thumbnail.png"
    
editor: visual

