project:
  type: website

website:
  title: "Proteomics blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/LKittinun/LKittinun.github.io
format:
  html:
    theme: flatly
    css: styles.css

editor: visual

