project:
  type: website
  output-dir: site

website:
  title: "Proteomics blog"
  site-url: "https://lkittinun.github.io/Proteomics"
  open-graph:
    site-name: "Proteomics blog"
    image: "https://lkittinun.github.io/Proteomics/site/thumbnail.png"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/LKittinun/LKittinun.github.io
format:
  html:
    theme: flatly
    css: styles.css

editor: visual

