project:
  type: website
  output-dir: site

website:
  title: "Proteomics blog"
  site-url: "http://lkittinun.github.io/Proteomics/site/index.html"
  open-graph:
    site-name: "Proteomics blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/LKittinun/LKittinun.github.io
format:
  html:
    theme: flatly
    css: styles.css

editor: visual

